forge "https://forge.puppet.com"

mod 'jlondon-phpmyadmin', '1.3.0'
mod 'puppetlabs-apache', '2.3.0'
mod 'puppetlabs-mysql', '5.1.0'
mod 'puppetlabs-ntp', '7.0.0'
mod 'saz-resolv_conf', '3.3.0'

exclusion 'php'
